-- Generated by ~/.config/scripts/gen-theme.sh from the wal palette.
-- look.lua dofile()s the generated hyprland-colors.lua last, so this overrides
-- the static colours there. Edit this template, not the output.

hl.config({
    general = {
        ["col.active_border"]   = { colors = { "rgba(ae95c7ff)", "rgba(c795aeff)" }, angle = 45 },
        ["col.inactive_border"] = "rgba(1c2023ff)",
    },
    decoration = {
        shadow = {
            color          = "rgba(ae95c7ff)",
            color_inactive = "rgba(1c2023ff)",
        },
    },
    group = {
        ["col.border_active"]   = { colors = { "rgba(ae95c7ff)", "rgba(c795aeff)" }, angle = 45 },
        ["col.border_inactive"] = "rgba(1c2023ff)",
        groupbar = {
            ["col.active"]   = "rgba(ae95c7ff)",
            ["col.inactive"] = "rgba(1c2023ff)",
        },
    },
})
