-- Generated by ~/.config/scripts/gen-theme.sh from the wal palette.
-- look.lua dofile()s the generated hyprland-colors.lua last, so this overrides
-- the static colours there. Edit this template, not the output.

hl.config({
    general = {
        ["col.active_border"]   = { colors = { "rgba(__PRIMARY_RGBA__)", "rgba(__SECONDARY_RGBA__)" }, angle = 45 },
        ["col.inactive_border"] = "rgba(__INACTIVE_RGBA__)",
    },
    decoration = {
        shadow = {
            color          = "rgba(__PRIMARY_RGBA__)",
            color_inactive = "rgba(__INACTIVE_RGBA__)",
        },
    },
    group = {
        ["col.border_active"]   = { colors = { "rgba(__PRIMARY_RGBA__)", "rgba(__SECONDARY_RGBA__)" }, angle = 45 },
        ["col.border_inactive"] = "rgba(__INACTIVE_RGBA__)",
        groupbar = {
            ["col.active"]   = "rgba(__PRIMARY_RGBA__)",
            ["col.inactive"] = "rgba(__INACTIVE_RGBA__)",
        },
    },
})
