-- ============================
-- LOOK & FEEL
-- ============================

local home = os.getenv("HOME")

hl.config({
    general = {
        gaps_in     = 4,
        gaps_out    = 4,
        border_size = 3,
        ["col.active_border"]   = { colors = { "rgba(c39e74ff)", "rgba(d2b898ff)" }, angle = 45 },
        ["col.inactive_border"] = "rgba(21170fff)",
        resize_on_border = true,
        allow_tearing    = false,
        layout           = "dwindle",
    },

    decoration = {
        rounding       = 8,
        rounding_power = 2,
        active_opacity   = 1.0,
        inactive_opacity = 1.0,
        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color          = "rgba(c39e74ee)",
            color_inactive = "rgba(1a1a1aee)",
        },
        blur = {
            enabled = true,
            size    = 3,
            passes  = 1,
        },
    },

    group = {
        ["col.border_active"]   = { colors = { "rgba(c39e74ff)", "rgba(d2b898ff)" }, angle = 45 },
        ["col.border_inactive"] = "rgba(21170fff)",
        groupbar = {
            ["col.active"]   = "rgba(c39e74ff)",
            ["col.inactive"] = "rgba(21170fff)",
        },
    },

    animations = {
        enabled = true,
    },

    dwindle = {
        preserve_split = true,
    },

    master = {
        new_status = "master",
    },

    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo   = true,
        vrr                     = 1,
    },

    -- HDR disabled (2026-08-01): tested with two genuinely HDR-capable paths (Pragmata's native
    -- HDR, Gothic 1 Remake's RenoDX mod) and Hyprland never actually engaged real HDR either way
    -- (hyprctl monitors kept reporting colorManagementPreset=srgb/currentFormat=XRGB8888 no matter
    -- what the game's own HDR toggle said). When the game-side tonemap did visibly change, it just
    -- looked worse (brighter/blurrier), not better, since the compositor was never really in HDR.
    -- On top of that, the BenQ EX2510S is only DisplayHDR 400 with no local dimming (~1136:1
    -- contrast), so even working HDR wouldn't look meaningfully different here anyway. Don't
    -- re-enable this without a real HDR panel and a less experimental Hyprland HDR implementation.
    -- Explicitly 0/disable, not just omitted: Hyprland's own default for this is 1 ("hdr"),
    -- so leaving it unset would still silently retry fullscreen auto-HDR.
    render = {
        cm_auto_hdr = 0,
    },
})

-- Bezier curves
hl.curve("easeOutQuint",   { type = "bezier", points = { { 0.23, 1.0  }, { 0.32, 1.0 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1.0 } } })
hl.curve("quick",          { type = "bezier", points = { { 0.15, 0.0  }, { 0.1,  1.0 } } })
hl.curve("linear",         { type = "bezier", points = { { 0.0,  0.0  }, { 1.0,  1.0 } } })

-- Animations
hl.animation({ leaf = "windows",          enabled = true, speed = 4.5, bezier = "easeOutQuint",    style = "popin 80%" })
hl.animation({ leaf = "windowsMove",      enabled = true, speed = 5.0, bezier = "quick"                                })
hl.animation({ leaf = "fade",             enabled = true, speed = 2.5, bezier = "quick"                                })
hl.animation({ leaf = "layers",           enabled = true, speed = 3.5, bezier = "easeOutQuint",    style = "slide"     })
hl.animation({ leaf = "workspaces",       enabled = true, speed = 2.2, bezier = "easeInOutCubic",  style = "slide"     })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 3.0, bezier = "easeOutQuint",    style = "slidevert" })
hl.animation({ leaf = "border",           enabled = true, speed = 3.0, bezier = "default"                              })
-- Slowly rotating gradient border (the signature Hyprland look).
hl.animation({ leaf = "borderangle",      enabled = true, speed = 50,  bezier = "linear",          style = "loop"      })

-- Theme color overrides: generated by gen-theme.sh, loaded last so a wallpaper
-- change re-colours borders / shadows / groupbar too.
local themeFile = home .. "/.config/theme/hyprland-colors.lua"
local f = io.open(themeFile, "r")
if f then
    f:close()
    dofile(themeFile)
end
