#!/bin/bash

set -e

WAL="$HOME/.cache/wal/colors"

[ -f "$WAL" ] || {
  echo "❌ no wal colors"
  exit 1
}

# ================================
# читаємо кольори
# ================================
bg=$(sed -n '1p' "$WAL")
error=$(sed -n '2p' "$WAL")
special=$(sed -n '4p' "$WAL")
primary=$(sed -n '5p' "$WAL")
secondary=$(sed -n '6p' "$WAL")
success=$(sed -n '7p' "$WAL")
fg=$(sed -n '8p' "$WAL")

# ================================
# fallback (дуже важливо)
# ================================
bg=${bg:-#000000}
fg=${fg:-#ffffff}
primary=${primary:-#33ccff}
secondary=${secondary:-#f9e2af}
error=${error:-#ff6b6b}
success=${success:-#a6e3a1}
special=${special:-#f5c2e7}

# ================================
# helpers
# ================================
strip() {
  echo "${1#\#}"
}

to_rgba() {
  hex="${1#\#}"

  # якщо щось зламалось — fallback
  if [ ${#hex} -lt 6 ]; then
    hex="000000"
  fi

  echo "${hex}ff"
}

hex_to_rgba_css() {
  r=$(printf "%d" 0x${1:1:2})
  g=$(printf "%d" 0x${1:3:2})
  b=$(printf "%d" 0x${1:5:2})
  echo "rgba($r,$g,$b,$2)"
}

hex_to_ansi() {
  r=$(printf "%d" 0x${1:1:2})
  g=$(printf "%d" 0x${1:3:2})
  b=$(printf "%d" 0x${1:5:2})
  echo "38;2;${r};${g};${b}"
}

# ================================
# готові значення
# ================================
BG=$(strip "$bg")
FG=$(strip "$fg")
FG_CSS="$fg"   # keeps # prefix — for CSS/SCSS use

PRIMARY="$primary"
SECONDARY="$secondary"
ERROR="$error"
SUCCESS="$success"
SPECIAL="$special"

WARNING="$secondary"

BG_ALPHA=$(hex_to_rgba_css "$bg" 0.85)
BG_STRONG=$(hex_to_rgba_css "$bg" 0.95)
BG_POPUP=$(hex_to_rgba_css "$bg" 0.97)
BG_SIDEBAR=$(hex_to_rgba_css "$bg" 0.98)

ALERT="$error"

PRIMARY_RGBA=$(to_rgba "$primary")
SECONDARY_RGBA=$(to_rgba "$secondary")
INACTIVE_RGBA=$(to_rgba "$bg")

# bare rrggbb (no '#') — for swaylock and other rgb-only consumers
PRIMARY_HEX=$(strip "$primary")
SECONDARY_HEX=$(strip "$secondary")
SUCCESS_HEX=$(strip "$success")
ERROR_HEX=$(strip "$error")

# CSS rgba() tints
PRIMARY_A10=$(hex_to_rgba_css "$primary" 0.1)
PRIMARY_A20=$(hex_to_rgba_css "$primary" 0.2)
PRIMARY_A30=$(hex_to_rgba_css "$primary" 0.3)
PRIMARY_A50=$(hex_to_rgba_css "$primary" 0.5)
FG_DIM=$(hex_to_rgba_css "$fg" 0.45)

PRIMARY_ANSI=$(hex_to_ansi "$primary")
SECONDARY_ANSI=$(hex_to_ansi "$secondary")
FG_ANSI=$(hex_to_ansi "$fg")

# ================================
# генератор
# ================================
generate() {
  template="$1"
  output="$2"

  [ -f "$template" ] || return 0

  sed \
    -e "s/__BG__/$BG/g" \
    -e "s/__FG__/$FG/g" \
    -e "s/__PRIMARY__/$PRIMARY/g" \
    -e "s/__SECONDARY__/$SECONDARY/g" \
    -e "s/__ERROR__/$ERROR/g" \
    -e "s/__SUCCESS__/$SUCCESS/g" \
    -e "s/__SPECIAL__/$SPECIAL/g" \
    -e "s/__WARNING__/$WARNING/g" \
    -e "s/__FG_CSS__/$FG_CSS/g" \
    -e "s/__BG_ALPHA__/$BG_ALPHA/g" \
    -e "s/__BG_STRONG__/$BG_STRONG/g" \
    -e "s/__BG_POPUP__/$BG_POPUP/g" \
    -e "s/__BG_SIDEBAR__/$BG_SIDEBAR/g" \
    -e "s/__ALERT__/$ALERT/g" \
    -e "s/__PRIMARY_RGBA__/$PRIMARY_RGBA/g" \
    -e "s/__SECONDARY_RGBA__/$SECONDARY_RGBA/g" \
    -e "s/__INACTIVE_RGBA__/$INACTIVE_RGBA/g" \
    -e "s/__PRIMARY_HEX__/$PRIMARY_HEX/g" \
    -e "s/__SECONDARY_HEX__/$SECONDARY_HEX/g" \
    -e "s/__SUCCESS_HEX__/$SUCCESS_HEX/g" \
    -e "s/__ERROR_HEX__/$ERROR_HEX/g" \
    -e "s/__PRIMARY_A10__/$PRIMARY_A10/g" \
    -e "s/__PRIMARY_A20__/$PRIMARY_A20/g" \
    -e "s/__PRIMARY_A30__/$PRIMARY_A30/g" \
    -e "s/__PRIMARY_A50__/$PRIMARY_A50/g" \
    -e "s/__FG_DIM__/$FG_DIM/g" \
    -e "s/__PRIMARY_ANSI__/$PRIMARY_ANSI/g" \
    -e "s/__SECONDARY_ANSI__/$SECONDARY_ANSI/g" \
    -e "s/__FG_ANSI__/$FG_ANSI/g" \
    "$template" >"$output"
}

# ================================
# застосування
# ================================

# Hyprland — look.lua dofile()s this last (the .conf variant is unused, the
# config is Lua now).
generate "$HOME/.config/theme/hyprland-colors.template.lua" \
  "$HOME/.config/theme/hyprland-colors.lua"

generate "$HOME/.config/wofi/style.template.css" \
  "$HOME/.config/wofi/style.css"

generate "$HOME/.config/fuzzel/fuzzel.template.ini" \
  "$HOME/.config/fuzzel/fuzzel.ini"

generate "$HOME/.config/ags/style.template.scss" \
  "$HOME/.config/ags/style.scss"

generate "$HOME/.config/swaync/style.template.css" \
  "$HOME/.config/swaync/style.css"

generate "$HOME/.config/swaylock/config.template" \
  "$HOME/.config/swaylock/config"

# hyprlock (inert until hyprlock is installed + wired in autostart/binds)
generate "$HOME/.config/hypr/hyprlock.template.conf" \
  "$HOME/.config/hypr/hyprlock.conf"

generate "$HOME/.config/fastfetch/config.template.jsonc" \
  "$HOME/.config/fastfetch/config.jsonc"

# ghostty — palette straight from wal; ghostty/config pulls it in via
# `config-file = theme-wal`.
{
  echo "# generated by gen-theme.sh — do not edit"
  echo "background = $bg"
  echo "foreground = $fg"
  echo "cursor-color = $primary"
  echo "selection-background = $primary"
  echo "selection-foreground = $bg"
  i=0
  while IFS= read -r c; do
    printf 'palette = %d=%s\n' "$i" "$c"
    i=$((i + 1))
  done < "$WAL"
} > "$HOME/.config/ghostty/theme-wal"

echo "✅ theme generated"

# ================================
# reload the rest
# ================================
swaync-client -rs 2>/dev/null || true    # reload swaync css
pkill -USR2 ghostty 2>/dev/null || true  # ghostty live config reload (newer builds)


# ================================
# reload ags
# ================================
if ags list 2>/dev/null | grep -q "^ags$"; then
  ags request reload
  # wait for instance to fully quit before starting fresh
  for i in $(seq 1 30); do
    ags list 2>/dev/null | grep -q "^ags$" || break
    sleep 0.1
  done
fi
ags run "$HOME/.config/ags" &
disown
